version: '3'

services:
  db:
    container_name: db
    image: mongo
    restart: on-failure
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: encryptwallback
    container_name: encryptwallback
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - db
    environment:
      - DB_CONNECT=${DB_CONNECT}
      - PORT=${PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - POST_SECRET=${POST_SECRET}
    networks:
      - app-network

volumes:
  dbdata:
  node_modules:  

networks:
  app-network:
    driver: bridge
